User.create(name: "Scott Cole", location: "Houston", username: "scotty", password: "cole1", balance: 4000, email: "scotty1@gmail.com")
User.create(name: "Ted Neben", location: "Houston", username: "teddy", password: "456", balance: 2000, email: "teddy1@gmail.com")
User.create(name: "Robert Tarantino", location: "Dallas", username: "logic", password: "123", balance: 263.37, email: "logic@hotmail.com")
User.create(name: "Marshall Mathers", location: "Austin", username: "eminem", password: "123", balance: 39.99, email: "eminem1@yahoo.com")
# = User.create(name: "")

Item.create(item_name: "Santa Cruz Bronson", user_id: 1, order_id: 1, location: "Houston", category: "Bicycles", condition: "New", price: 4000, description: "Super gnarly 2020 Bronson. Shreds anything!")
Item.create(item_name: "Macbook Pro", user_id: 2, order_id: 2,  location: "Houston", category: "Computers", condition: "New", price: 2000 , description: "2020 Macbook Pro. Hot buy!")
Item.create(item_name: "Gaming Chair", user_id: 3, order_id: 3, location: "Austin", category: "Furniture", condition: "Used Like New", price: 250, description: "Awesome chair. Will raise KD and stream followers")
Item.create(item_name: "Xbox 360 Controller", user_id: 3, order_id: 4, location: "Austin", category: "Gaming", condition: "Used Not Great", price: 13.37, description: "Heavily used Xbox 360 Controller, good for mod body")
Item.create(item_name: "Converse High Tops", user_id: 4, order_id: 5, location: "Dallas", category: "Clothing", condition: "New", price: 39.99, description: "Size 11 Mens High-Top Chucks")
Item.create(item_name: "Toilet Seat", user_id: 2,location: "Houston", category: "Household", condition: "Used Not Great", price: 21.65, description: "White plastic toilet seat, color has faded a bit and worn around the sides...naturally")
Item.create(item_name: "Coffee Mug", user_id: 1, location: "Austin", category: "Household", condition: "Used Like New", price: 4.99, description: "Black Ceramic Coffee Mug, says All Your Base Are Belong To Us")
Item.create(item_name: "Hyper X Cloud", user_id: 2,location: "Houston", category: "Computers", condition: "New", price: 69.99, description: "Sealed Hyper X Cloud Wired Headset")
Item.create(item_name: "Bike Bell", user_id: 1, location: "Houston", category: "Bicycles", condition: "Used Not Great", price: 10.00, description: "Stainless Steel Desk Bell fashioned for a bike... Ding in style")
Item.create(item_name: "Scooter", user_id: 3,  location: "Dallas", category: "Active", condition: "New", price: 100, description: "Scoots around just fine. Selling because I don't go outside anymore.")
Item.create(item_name: "Pontiac Aztec Transmission", user_id: 4,  location: "Austin", category: "Auto", condition: "Used Not Great", price: 1000, description: "Needs major work done on it.")

# Item.create(item_name: "", user_id:,  location: "", category: "", condition: "", price: , description: "")

Order.create(seller: 1, buyer: 2, item_id: 1, order_type: "Local", shipping?: false, shipping_address: nil, meeting_location: "123 Fake Street. Houston, TX 77777", date_time: "2020-07-27 16:00:00 -0500")
Order.create(seller: 2, buyer: 1, item_id: 2, order_type: "Local", shipping?: false, shipping_address: nil, meeting_location: "456 Made-up Street. Houston, TX 77777", date_time: "2020-07-28 18:00:00 -0500")
Order.create(seller: 3, buyer: 1, item_id: 3, order_type: "Shipment", shipping?: true, shipping_address: "Scott's House, Houston, TX 77777", meeting_location: nil)
Order.create(seller: 3, buyer: 2, item_id: 4, order_type: "Shipment", shipping?: true, shipping_address: "Ted's, Houston, TX 77777", meeting_location: nil)
Order.create(seller: 4, buyer: 3, item_id: 5, order_type: "Shipment", shipping?: true, shipping_address: "Bobby's House, Houston, TX 77777", meeting_location: nil)